add FreeBSD support
iv-org/smart-ipv6-rotator pull request #11
Opened 2023-12-21 02:10 UTC by TechnicalSuwako

2023-12-21 07:17 UTC, unixfox requested changes

2023-12-21 07:17 UTC, unixfox commented on smart-ipv6-rotator-freebsd.py
> +            subprocess.run(['route', '-6', 'add', ipv6_range, gateway], check=True)
I'm not entirely sure if this replicate the same behavior as the Linux version.

This command does not add a route that will be forced to use the new ipv6 address added.

In fact this command is useless because the default gateway already cover the ipv6 ranges that will be added. Hence the reason why it's called default gateway.

2023-12-21 10:54 UTC, TechnicalSuwako commented on smart-ipv6-rotator-freebsd.py
> +            subprocess.run(['route', '-6', 'add', ipv6_range, gateway], check=True)
左はdebian、右はfreebsd
Debian on the left, freebsd on the right

![Screenshot_20231221_195413](https://github.com/iv-org/smart-ipv6-rotator/assets/15627184/90aa6372-0c8a-4665-ba4c-f1639d62ccd7)

2023-12-21 11:02 UTC, unixfox commented on smart-ipv6-rotator-freebsd.py
> +            subprocess.run(['route', '-6', 'add', ipv6_range, gateway], check=True)
what are you trying to say by this? I don't understand.

2023-12-21 11:39 UTC, TechnicalSuwako commented on smart-ipv6-rotator-freebsd.py
> +            subprocess.run(['route', '-6', 'add', ipv6_range, gateway], check=True)
freebsdでこのスクリプトが問題無しで動いている事
This script is running without any problems on freebsd.

2023-12-21 11:51 UTC, unixfox commented on smart-ipv6-rotator-freebsd.py
> +            subprocess.run(['route', '-6', 'add', ipv6_range, gateway], check=True)
But that's not the point of my comment.

The issue with your script is that it doesn't force to the new ipv6 address that the script assigned. So it is possible that the outgoing ipv6 address may not change and thus youtube will still block the IP.

Read again what I said in my first comment please.

2023-12-27 12:25 UTC, unixfox commented
Closing due to lack of replies.

2023-12-27 12:25 UTC, closed without merging