Add parameter cron for disabling checks not useful when being instantiated by CRON
iv-org/smart-ipv6-rotator pull request #25
Opened 2024-06-05 07:22 UTC by unixfox

This will help with these issues:
- https://github.com/iv-org/smart-ipv6-rotator/issues/13
- https://github.com/iv-org/smart-ipv6-rotator/issues/3

Basically, the HTTP check may not be useful if the script is launched by CRON because the HTTP check is only for telling people that their setup does not work.

People can disable this check by passing `--cron`.

2024-06-05 07:23 UTC, unixfox commented
@WardPearce if you can review what I have done :). thank you

2024-06-07 01:59 UTC, WardPearce commented
> @WardPearce if you can review what I have done :). thank you

Yes can do, on holiday currently but will check this briefly

2024-06-07 02:01 UTC, WardPearce requested changes
Some minor suggestions

2024-06-07 02:01 UTC, WardPearce commented on smart_ipv6_rotator/__init__.py
> +    if cron == False:
```suggestion
    if not cron:
```

2024-06-07 02:05 UTC, WardPearce commented on smart_ipv6_rotator/__init__.py
> +        "--cron",
Probably shouldn't be a shared parameter, as only used for run.

2024-06-07 02:24 UTC, WardPearce commented
Following needs to be updated too
https://github.com/iv-org/smart-ipv6-rotator/blob/677835d0be84f1a2210f41eeb26f5d5a80ac3319/README.md?plain=1#L60

2024-06-30 10:46 UTC, unixfox commented on smart_ipv6_rotator/__init__.py
> +        "--cron",
What do you mean by that?

2024-06-30 10:49 UTC, WardPearce commented on smart_ipv6_rotator/__init__.py
> +        "--cron",
"SHARED_OPTIONS" is options what are shared between all the commands.
If a option is only specific to a command, it should prob be added like so https://github.com/iv-org/smart-ipv6-rotator/blob/skip-http-checks-cron/smart_ipv6_rotator/__init__.py#L266

2024-08-15 11:11 UTC, unixfox commented on smart_ipv6_rotator/__init__.py
> +        "--cron",
thanks. I moved to a static option.

2024-08-15 11:14 UTC, merged